#! /bin/bash

git diff --cached --name-only | grep ".php$" | grep -v "^views/" | awk '{cmd="./vendor/bin/phpcbf "$0;system(cmd)}'

 git diff --cached --name-only | grep ".php$" | grep -v "^views/" | php -l

./vendor/bin/phpunit ./tests

./sonar.sh > /dev/null 2>&1 &

